from typing import Any, NoReturn

class WriteBackResult:
    edited_files: dict[str, str]
    changed_files: list[str]
    changed_declarations: list[str]
    mode: str
    validation_ok: bool
    validation_message: str | None

class ModelBuilder:
    def __init__(self, validate_each_mutation: bool = True) -> None: ...
    def add_package(self, target_file: str, name: str) -> WriteBackResult: ...
    def add_definition(
        self,
        container: str,
        keyword: str,
        name: str,
        specializes: list[str] | None = None,
    ) -> WriteBackResult: ...
    def add_usage(
        self,
        container: str,
        keyword: str,
        name: str,
        ty: str | None = None,
        specializes: list[str] | None = None,
    ) -> WriteBackResult: ...
    def set_expression(self, element: str, expression: str | None = None) -> WriteBackResult: ...
    def set_attribute(self, element: str, attribute: str, value: Any) -> WriteBackResult: ...
    def rendered_files(self) -> dict[str, str]: ...
    def compile_model(self) -> Any: ...

class PyPartRef:
    id: str
    name: str
    kind: str
    element_kind: str
    parent_id: str | None
    depth: int
    def attr(self, name: str) -> str | None: ...
    def json(self) -> str: ...

class PyKirElement:
    id: str
    label: str
    kind: str
    layer: int
    def json(self) -> str: ...

class PyWorkspace:
    @staticmethod
    def open(path: str) -> PyWorkspace: ...
    def model(self) -> str: ...
    def graph(self) -> str: ...
    def parts(self) -> list[PyPartRef]: ...
    def element(self, id: str) -> PyKirElement | None: ...
    def compile(self) -> Any: ...
    def list_analysis_cases(self) -> NoReturn: ...
    def run_analysis(self, case_id: str) -> NoReturn: ...
